exec: ../dist/build/sig-service/sig-service
args:
    - production
host: sig-service.fpcenter.io

# Use the following to automatically copy your bundle upon creation via `yesod
# keter`. Uses `scp` internally, so you can set it to a remote destination
# copy-to: user@host:/opt/keter/incoming
